apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-deployment
  labels:
    app: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
        - name: microservice
          image: client-side-lb/microservice:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: HTTP_PORT
              value: "8080"
          ports:
            - containerPort: 8080
